## Linear Algebra (Vector) - NGC 04 - FTDS Offline

In [126]:
import numpy as np
from numpy import array, diag
from numpy.linalg import inv, det, eig

In [127]:
# No. 1
V = np.array ([17, 22, 19])
V

array([17, 22, 19])

In [128]:
# No. 2
A = np.array ([17, 22, 19])

B = np.array ([10, 20, 11])

C = np.array ([5, 12, 9])

In [129]:
A + B

array([27, 42, 30])

In [130]:
B - C

array([5, 8, 2])

In [131]:
# Cara 1
A.dot(C)

520

In [132]:
# Cara 2
A @ C

520

In [133]:
A * B

array([170, 440, 209])

In [134]:
np.linalg.norm(A)

33.67491648096547

In [135]:
cos_theta = (A @ B) / (np.linalg.norm(A) * np.linalg.norm(B))
cos_theta

0.9759590023331435

In [136]:
# No. 3
u = np.array([2, 5])
v = np.array([3, 1])

In [137]:
w = np.array([[u], [v]])
w

array([[[2, 5]],

       [[3, 1]]])