## Linear Algebra (Matrix) - NGC 05 - FTDS Offline

In [2]:
import numpy as np
from numpy import array, diag
from numpy.linalg import inv, det, eig

In [3]:
# No. 1
T = array([[[23, 50], [7, 12]], [[57, 67], [99, 43]], [[75, 21], [57, 12]], [[87, 26], [18, 84]]])
T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [4]:
# No. 2
A = array([[23, 50, 19], [7 ,12, 109], [57, 67, 98]])
B = array([17, 22, 19]) # Vektor engga usah dipusingin, memang bentuknya pasti begini walaupun terlihat beda di symbolic form.
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [5]:
# No. 3
A = ([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
A

[[23, 50, 19], [7, 12, 109], [57, 67, 98]]

In [6]:
np.transpose(A)

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [7]:
det(A)

131344.0000000002

In [8]:
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])